export const GET_ALL_POKEMON_SUCCESS = "GET_ALL_POKEMON_SUCCESS";
export const GET_ALL_POKEMON_START = "GET_ALL_POKEMON_START";
export const GET_ALL_POKEMON_FAIL = "GET_ALL_POKEMON_FAIL";

export const GET_ALL_POKEMON_TOTAL = "GET_ALL_POKEMON_TOTAL";
export const GET_ALL_POKEMON_NEXT = "GET_ALL_POKEMON_NEXT";
export const GET_ALL_POKEMON_NEXT_NULL = "GET_ALL_POKEMON_NEXT_NULL";
export const GET_ALL_POKEMON_MORE = "GET_ALL_POKEMON_MORE";

export const LOAD_MORE_START = "LOAD_MORE_START";
export const LOAD_MORE_SUCCESS = "LOAD_MORE_SUCCESS";
export const LOAD_MORE_FAIL = "LOAD_MORE_FAIL";
