export const GET_ALL_POKEMON_SUCCESS = "GET_ALL_POKEMON_SUCCESS";
export const GET_ALL_POKEMON_START = "GET_ALL_POKEMON_START";
export const GET_ALL_POKEMON_FAIL = "GET_ALL_POKEMON_FAIL";

export const GET_ALL_POKEMON_TOTAL = "GET_ALL_POKEMON_TOTAL";
export const GET_ALL_POKEMON_NEXT = "GET_ALL_POKEMON_NEXT";
export const GET_ALL_POKEMON_NEXT_NULL = "GET_ALL_POKEMON_NEXT_NULL";
export const GET_ALL_POKEMON_MORE = "GET_ALL_POKEMON_MORE";

export const LOAD_MORE_START = "LOAD_MORE_START";
export const LOAD_MORE_SUCCESS = "LOAD_MORE_SUCCESS";
export const LOAD_MORE_FAIL = "LOAD_MORE_FAIL";

export const SET_COLLECTION_DEFAULT = "SET_COLLECTION_DEFAULT";

export const ADD_COLLECTION_SUCCESS = "ADD_COLLECTION_SUCCESS";
export const ADD_COLLECTION_FAILED = "ADD_COLLECTION_FAILED";

export const DELETE_COLLECTION_SUCCESS = "DELETE_COLLECTION_SUCCESS";
export const DELETE_COLLECTION_FAILED = "DELETE_COLLECTION_FAILED";
